In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import VarianceThreshold

dftrain = pd.read_csv(r"C:\Users\SavarimuthuC\train.csv")
dftest = pd.read_csv(r"C:\Users\SavarimuthuC\test.csv")

In [19]:
dftrain.shape

(4209, 378)

In [20]:
# get number of unique values for each column
countstrain = dftrain.var()
countstest = dftest.var()

In [21]:
# record columns to delete
to_deltrain = [i for i,v in enumerate(countstrain) if v == 0]
print(to_deltrain)
to_deltest = [i for i,v in enumerate(countstest) if v == 0]
print(to_deltest)

[3, 83, 97, 219, 221, 254, 275, 276, 279, 283, 315, 332]
[242, 243, 280, 281, 353]


In [22]:
# drop useless columns where var=0
dftrain.drop(to_deltrain, inplace=True)
dftest.drop(to_deltest, inplace=True)

In [38]:
# remove ID and Y from the data as they are not used for learning
# usable_columns = list(set(dftrain.columns) - set(['y']))
y_train = dftrain['y'].values
id_test = dftest['ID'].values
# x_train = dftrain[usable_columns]
# x_test = dftest[usable_columns]
# x_train.head()

In [23]:
dftrain.shape
dftest.shape


(4204, 377)

In [24]:
# Check for null values for test and train sets

def check_missing_values(df):
    if df.isnull().any().any():
        print("Missing Values are Present")
    else:
        print("No Missing Values")
check_missing_values(dftrain)
check_missing_values(dftest)

No Missing Values
No Missing Values


In [26]:
# Check for unique values for test and train sets

def check_unique_values(df):
    if df.nunique().any():
        print("Values are Unique")
    else:
        print("Not Unique")
check_unique_values(dftrain)
check_unique_values(dftest)

Values are Unique
Values are Unique


In [28]:
dftrain.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   
5  18   92.93   t  b   e  c  d  g  h  s  ...     0     0     1     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
4     0     0     0     0     0  
5     0     0     0     0     0  

[5 rows x 378 columns]

In [12]:
x_train.head()

def handle_non_numerical_data(df):
    columns = df.columns.values
    for column in columns:
        text_digit_vals = {}
        def convert_to_int(val):
            return text_digit_vals[val]

        if df[column].dtype != np.int64 and df[column].dtype != np.float64:
            column_contents = df[column].values.tolist()
            unique_elements = set(column_contents)
            x = 0
            for unique in unique_elements:
                if unique not in text_digit_vals:
                    text_digit_vals[unique] = x
                    x+=1

            df[column] = list(map(convert_to_int, df[column]))

    return df

x_train_numeric  = handle_non_numerical_data(x_train)
x_test_numeric  = handle_non_numerical_data(x_test)


C:\Users\SavarimuthuC\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [31]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

for col in dftrain:
    cardinality = len(np.unique(dftrain[col]))
    if cardinality > 2:
        dftrain[col]= label.fit_transform(dftrain[col]) 
        print(dftrain[col].unique())

[   0    1    2 ... 4194 4195 4196]
[2462  365   69 ...  188 1762  279]
[32 20 40  9 36 43 31 29 39 35 19 27 44 45  7  8 10 46 37 15 12 42  5  0
 26  6 25 13 24  1 22 14 30 38 21 18 23 41  4 16 34 33 17 11  3 28  2]
[23 21 24  3 19 13 20  1  4  0  6  9 26 11 16 22 17 15 25  5  7 10 14 12
  8 18  2]
[17 19 34 25 16 14 38  7  8 33  0 31  3 39 26 24  5 21  2 13 27 29 20 42
 22 12  9 28 41 18 40 11 43  6 36 10 30 37  4 32  1 23 35 15]
[0 4 2 5 3 1 6]
[3 1 2 0]
[24 28 27 12 11 10 14 13  9  8  5  6  1  2  3  4  7 16 15 18 17 20 21 23
 22 25 26 19  0]
[ 9 11  3  7  8  0  6  2 10  4  5  1]
[14 23 13 18  0  7  4 15 12 10  3  8 21  9  1 16 22  6 24 11  5 20 17 19
  2]


In [33]:
for col in dftest:
    cardinality = len(np.unique(dftest[col]))
    if cardinality > 2:
        dftest[col]= label.fit_transform(dftest[col]) 
        print(dftest[col].unique())

[   0    1    2 ... 4201 4202 4203]
[21 42 45 47 46 29 12 38 20  8 31 48  6 27 44  7 23 37 33 41  3 19 15 13
 17 36 34  0 28  5 32  4 22  9 18 14 40 11 43 35 26  1 16 25 30 10  2 39
 24]
[23  3 13 20  1 19  0 10 17  4 16 14 26  6  9 24  8 12 25 21 22  5 11 18
 15  7  2]
[34  8 17  4 38 24 26 10 33  0 16  6 37 32  9 23 14 13  2  5 22 29 30 27
 15 35 19 39 44 43 21 25 18 28 12 31 42  1 41 36  7  3 11 20 40]
[5 0 2 4 3 6 1]
[3 1 0 2]
[26  9  0 31 30 29 14 13 12 16 15 11 10  6  7  2  3  4  5  8 18 17 20 19
 22 23 25 24 27 28 21  1]
[ 0  6  9 11  8  3  5  7  2 10  4  1]
[22 24  9 13 12 18  0 21 17 14 19  7  2 10 15 20  3  6  1 16  4 11  5  8
 23]


In [34]:
# Perform Dimensionality reduction
from sklearn.decomposition import PCA
pca = PCA()

x_pca_train = pca.fit_transform(dftrain)
x_pca_train = pd.DataFrame(x_pca_train)

x_pca_test = pca.fit_transform(dftest)
x_pca_test = pd.DataFrame(x_pca_test)

In [35]:
x_pca_train.head()

0            1          2          3          4          5    \
0  2154.185794  1165.200743  -4.786781  -0.702854  14.482671   1.745786   
1  2056.077052  -929.474620   5.288395   2.149257  10.346804   2.742629   
2  2041.377578 -1225.024522  22.203674  13.223935   9.777788  13.155176   
3  2042.159573 -1188.023668  22.444627  13.600387   8.220965   2.708829   
4  2071.086776  -542.790133  -7.292848   9.519634  -4.629576   7.456396   

         6         7         8         9    ...           368           369  \
0  19.817401 -2.780592  3.649437  2.351891  ...  3.958251e-16  1.797349e-15   
1  23.972400 -4.574451 -0.070812  0.471730  ... -2.181643e-13  1.888493e-14   
2  22.881499 -2.293172  1.947309  0.253023  ... -1.323751e-14  1.236964e-13   
3   8.282528  3.681343 -0.926964  0.911493  ...  1.402916e-14 -1.201017e-13   
4   6.623916  0.247062  1.278742 -0.677049  ...  1.454530e-13  5.172425e-14   

            370           371           372           373           374  \
0  1.355576e-15  5.710988e-17  1.077516e-15  9.419217e-16  8.722641e-16   
1 -1.024682e-13 -5.163749e-14 -1.214563e-13 -1.194445e-13  8.569337e-14   
2 -1.199190e-13 -1.265491e-13  1.056890e-13 -7.657981e-14  2.045905e-13   
3  1.226301e-13  1.266633e-13 -1.035339e-13  7.846365e-14 -2.028459e-13   
4 -1.610029e-13  8.323005e-14 -1.158930e-13  2.557448e-16 -1.331470e-13   

            375           376           377  
0 -2.190205e-16  1.011035e-15  1.592399e-17  
1 -1.472374e-13  1.799771e-14 -4.595648e-16  
2  3.256819e-14  1.292167e-13 -3.473189e-16  
3 -3.300623e-14 -1.271946e-13  3.791668e-16  
4 -8.493254e-14 -2.910990e-14 -1.637478e-16  

[5 rows x 378 columns]

In [39]:
from xgboost import xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

x_train, x_test, y_train, y_test = train_test_split(
        x_pca_train, 
        y_train, test_size=0.2, 
        random_state=4242)

d_train = xgb.DMatrix(x_train, label=y_train)
d_valid = xgb.DMatrix(x_tes, label=y_valid)
d_test = xgb.DMatrix(x_pca_test)

params = {}
params['objective'] = 'reg:linear'
params['eta'] = 0.02
params['max_depth'] = 4

def xgb_r2_score(preds, dtrain):
    labels = dtrain.get_label()
    return 'r2', r2_score(labels, preds)

watchlist = [(d_train, 'train'), (d_valid, 'valid')]

clf = xgb.train(params, d_train, 
                1000, watchlist, early_stopping_rounds=50, 
                feval=xgb_r2_score, maximize=True, verbose_eval=10)

ModuleNotFoundError: No module named 'xgboost'

In [40]:

pwd


'C:\\Users\\SavarimuthuC'